language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"  

# environment
env:
  - DJANGO=2.1.4

branches:
  only:
    - master

# database services
services: postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python manage.py test
